// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findByUsername = `-- name: FindByUsername :one
SELECT id, username, password, created_at, auth_at FROM auth WHERE username = $1
`

func (q *Queries) FindByUsername(ctx context.Context, username string) (Auth, error) {
	row := q.db.QueryRowContext(ctx, findByUsername, username)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.AuthAt,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO auth (id, username, password, created_at, auth_at)
VALUES ($1, $2, $3, $4, $5)
`

type SaveParams struct {
	ID        uuid.UUID
	Username  string
	Password  string
	CreatedAt time.Time
	AuthAt    sql.NullTime
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.ExecContext(ctx, save,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.CreatedAt,
		arg.AuthAt,
	)
	return err
}

const updateAuth = `-- name: UpdateAuth :exec
UPDATE auth
SET auth_at = $2
WHERE username = $1
`

type UpdateAuthParams struct {
	Username string
	AuthAt   sql.NullTime
}

func (q *Queries) UpdateAuth(ctx context.Context, arg UpdateAuthParams) error {
	_, err := q.db.ExecContext(ctx, updateAuth, arg.Username, arg.AuthAt)
	return err
}
