// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteCartItem, arg.CartID, arg.ProductID)
	return err
}

const findCartByBuyerID = `-- name: FindCartByBuyerID :one
SELECT id, buyer_id, created_at FROM carts WHERE buyer_id = $1
`

func (q *Queries) FindCartByBuyerID(ctx context.Context, buyerID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, findCartByBuyerID, buyerID)
	var i Cart
	err := row.Scan(&i.ID, &i.BuyerID, &i.CreatedAt)
	return i, err
}

const findCartItems = `-- name: FindCartItems :many
SELECT cart_id, product_id, quantity FROM cart_items WHERE cart_id = $1
`

func (q *Queries) FindCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, findCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(&i.CartID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCart = `-- name: SaveCart :exec
INSERT INTO carts (id, buyer_id, created_at) VALUES ($1, $2, $3)
`

type SaveCartParams struct {
	ID        uuid.UUID
	BuyerID   uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) SaveCart(ctx context.Context, arg SaveCartParams) error {
	_, err := q.db.ExecContext(ctx, saveCart, arg.ID, arg.BuyerID, arg.CreatedAt)
	return err
}

const saveCartItem = `-- name: SaveCartItem :exec
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
    ON CONFLICT (cart_id, product_id) DO UPDATE SET quantity = EXCLUDED.quantity
`

type SaveCartItemParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

func (q *Queries) SaveCartItem(ctx context.Context, arg SaveCartItemParams) error {
	_, err := q.db.ExecContext(ctx, saveCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	return err
}
