// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findAllCategories = `-- name: FindAllCategories :many
SELECT id, name, parent_id, level, status, attribute_set_id, created_at FROM categories
`

func (q *Queries) FindAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, findAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Level,
			&i.Status,
			&i.AttributeSetID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCategoryByID = `-- name: FindCategoryByID :one
SELECT id, name, parent_id, level, status, attribute_set_id, created_at FROM categories WHERE id = $1
`

func (q *Queries) FindCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, findCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Level,
		&i.Status,
		&i.AttributeSetID,
		&i.CreatedAt,
	)
	return i, err
}

const findCategoryByIDForUpdate = `-- name: FindCategoryByIDForUpdate :one
SELECT id, name, parent_id, level, status, attribute_set_id, created_at FROM categories WHERE id = $1 FOR UPDATE
`

func (q *Queries) FindCategoryByIDForUpdate(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, findCategoryByIDForUpdate, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Level,
		&i.Status,
		&i.AttributeSetID,
		&i.CreatedAt,
	)
	return i, err
}

const saveCategory = `-- name: SaveCategory :exec
INSERT INTO categories (id, name, parent_id, level, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type SaveCategoryParams struct {
	ID        uuid.UUID
	Name      string
	ParentID  uuid.NullUUID
	Level     int32
	CreatedAt time.Time
}

func (q *Queries) SaveCategory(ctx context.Context, arg SaveCategoryParams) error {
	_, err := q.db.ExecContext(ctx, saveCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Level,
		arg.CreatedAt,
	)
	return err
}
