// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type OrderStatus string

const (
	OrderStatusCREATED   OrderStatus = "CREATED"
	OrderStatusPROCESS   OrderStatus = "PROCESS"
	OrderStatusSUCCESS   OrderStatus = "SUCCESS"
	OrderStatusFAIL      OrderStatus = "FAIL"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCARD   PaymentMethod = "CARD"
	PaymentMethodCASH   PaymentMethod = "CASH"
	PaymentMethodWALLET PaymentMethod = "WALLET"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod
	Valid         bool // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type UserRole string

const (
	UserRoleADMIN UserRole = "ADMIN"
	UserRoleBUYER UserRole = "BUYER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Auth struct {
	ID        uuid.UUID
	Username  string
	Password  string
	CreatedAt time.Time
	AuthAt    sql.NullTime
}

type Cart struct {
	ID        uuid.UUID
	BuyerID   uuid.UUID
	CreatedAt time.Time
}

type CartItem struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

type Category struct {
	ID             uuid.UUID
	Name           string
	ParentID       uuid.NullUUID
	Level          int32
	Status         bool
	AttributeSetID sql.NullInt32
	CreatedAt      time.Time
}

type Order struct {
	ID            uuid.UUID
	BuyerID       uuid.UUID
	Status        OrderStatus
	Total         string
	Currency      string
	PaymentMethod PaymentMethod
	CreatedAt     time.Time
}

type OrderItem struct {
	OrderID      uuid.UUID
	ProductID    uuid.UUID
	Quantity     int32
	PriceAtOrder string
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	CreatedAt   time.Time
	Currency    string
	Stock       int32
	SellerID    uuid.UUID
	UpdatedAt   time.Time
	Active      bool
	Attributes  pqtype.NullRawMessage
	CategoryIds []uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	Surname   sql.NullString
	Role      UserRole
	AuthAt    sql.NullTime
	CreatedAt time.Time
	Email     string
	Enabled   bool
}
