// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findOrderByID = `-- name: FindOrderByID :one
SELECT id, buyer_id, status, total, currency, payment_method, created_at FROM orders WHERE id = $1
`

func (q *Queries) FindOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, findOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.Status,
		&i.Total,
		&i.Currency,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const findOrderItems = `-- name: FindOrderItems :many
SELECT order_id, product_id, quantity, price_at_order FROM order_items WHERE order_id = $1
`

func (q *Queries) FindOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, findOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceAtOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrdersByBuyerID = `-- name: FindOrdersByBuyerID :many
SELECT id, buyer_id, status, total, currency, payment_method, created_at FROM orders WHERE buyer_id = $1
`

func (q *Queries) FindOrdersByBuyerID(ctx context.Context, buyerID uuid.UUID) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, findOrdersByBuyerID, buyerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.Status,
			&i.Total,
			&i.Currency,
			&i.PaymentMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOrder = `-- name: SaveOrder :exec
INSERT INTO orders (id, buyer_id, status, total, currency, payment_method, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveOrderParams struct {
	ID            uuid.UUID
	BuyerID       uuid.UUID
	Status        OrderStatus
	Total         string
	Currency      string
	PaymentMethod PaymentMethod
	CreatedAt     time.Time
}

func (q *Queries) SaveOrder(ctx context.Context, arg SaveOrderParams) error {
	_, err := q.db.ExecContext(ctx, saveOrder,
		arg.ID,
		arg.BuyerID,
		arg.Status,
		arg.Total,
		arg.Currency,
		arg.PaymentMethod,
		arg.CreatedAt,
	)
	return err
}

const saveOrderItem = `-- name: SaveOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity, price_at_order)
VALUES ($1, $2, $3, $4)
`

type SaveOrderItemParams struct {
	OrderID      uuid.UUID
	ProductID    uuid.UUID
	Quantity     int32
	PriceAtOrder string
}

func (q *Queries) SaveOrderItem(ctx context.Context, arg SaveOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, saveOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtOrder,
	)
	return err
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderParams struct {
	ID     uuid.UUID
	Status OrderStatus
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateOrder, arg.ID, arg.Status)
	return err
}
