// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, description, price, created_at, currency, stock, seller_id, updated_at, active, attributes, category_ids FROM products WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.Currency,
		&i.Stock,
		&i.SellerID,
		&i.UpdatedAt,
		&i.Active,
		&i.Attributes,
		pq.Array(&i.CategoryIds),
	)
	return i, err
}

const getProductList = `-- name: GetProductList :many
SELECT id, name, description, price, created_at, currency, stock, seller_id, updated_at, active, attributes, category_ids FROM products
WHERE
    ($1::uuid IS NULL OR $1::uuid = ANY(category_ids))
  AND ($2::numeric IS NULL OR price >= $2::numeric)
  AND ($3::numeric IS NULL OR price <= $3::numeric)
    LIMIT $5 OFFSET $4
`

type GetProductListParams struct {
	CategoryID uuid.NullUUID
	MinPrice   sql.NullString
	MaxPrice   sql.NullString
	Offset     int32
	Limit      int32
}

func (q *Queries) GetProductList(ctx context.Context, arg GetProductListParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductList,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.Currency,
			&i.Stock,
			&i.SellerID,
			&i.UpdatedAt,
			&i.Active,
			&i.Attributes,
			pq.Array(&i.CategoryIds),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveProduct = `-- name: SaveProduct :exec
INSERT INTO products (id, name, description, price, currency, stock, seller_id, created_at, updated_at, active, attributes, category_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type SaveProductParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Currency    string
	Stock       int32
	SellerID    uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Active      bool
	Attributes  pqtype.NullRawMessage
	CategoryIds []uuid.UUID
}

func (q *Queries) SaveProduct(ctx context.Context, arg SaveProductParams) error {
	_, err := q.db.ExecContext(ctx, saveProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.Stock,
		arg.SellerID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Active,
		arg.Attributes,
		pq.Array(arg.CategoryIds),
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = $2, description = $3, price = $4, stock = $5, updated_at = $6, active = $7, category_ids = $8
WHERE id = $1
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       string
	Stock       int32
	UpdatedAt   time.Time
	Active      bool
	CategoryIds []uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.UpdatedAt,
		arg.Active,
		pq.Array(arg.CategoryIds),
	)
	return err
}
