// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findUserByID = `-- name: FindUserByID :one
SELECT id, username, surname, role, auth_at, created_at, email, enabled FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Surname,
		&i.Role,
		&i.AuthAt,
		&i.CreatedAt,
		&i.Email,
		&i.Enabled,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, username, surname, role, auth_at, created_at, email, enabled FROM users WHERE username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Surname,
		&i.Role,
		&i.AuthAt,
		&i.CreatedAt,
		&i.Email,
		&i.Enabled,
	)
	return i, err
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO users (id, username, surname, role, email, created_at, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveUserParams struct {
	ID        uuid.UUID
	Username  string
	Surname   sql.NullString
	Role      UserRole
	Email     string
	CreatedAt time.Time
	Enabled   bool
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.ExecContext(ctx, saveUser,
		arg.ID,
		arg.Username,
		arg.Surname,
		arg.Role,
		arg.Email,
		arg.CreatedAt,
		arg.Enabled,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $2, surname = $3, email = $4, enabled = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID       uuid.UUID
	Username string
	Surname  sql.NullString
	Email    string
	Enabled  bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Surname,
		arg.Email,
		arg.Enabled,
	)
	return err
}
